name: tests-tickets

on: 
  pull_request:
    paths:
      - 'tickets/**' #only do changes for auth service
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd tickets && npm install && npm run test:ci
