name: tests-payments

on: 
  pull_request
    paths:
      - 'payments/**' #only do changes for auth service
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd payments && npm install && npm run test:ci
